### ISSUE TITLE
Plugin causes PHP fatal error with MultilingualPress

### ISSUE THREAD

**Issue by ahmed-sigmalux** [inpsyde/translation-cache#3]
1. Install and activate translation cache and MultilingualPress plugins.
2. Add a new site and select any existing site for "based on". 
3. Click submit and PHP crashes, generating a 50x backend error.

Here is the error from my debug log:

```
[03-Oct-2017 04:39:26 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Inpsyde\TranslationCache\MoCache::on_theme_switch(), 2 passed in /var/www/mysite.com/wp-includes/class-wp-hook.php on line 298 and exactly 3 expected in /var/www/mysite.com/wp-content/plugins/translation-cache/src/MoCache.php:119
Stack trace:
#0 /var/www/mysite.com/wp-includes/class-wp-hook.php(298): Inpsyde\TranslationCache\MoCache::on_theme_switch('My Theme', Object(WP_Theme))
#1 /var/www/mysite.com/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/mysite.com/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/mysite.com/wp-content/plugins/multilingual-press/inc/copy-site/Mlp_Duplicate_Blogs.php(150): do_action('switch_theme', 'My Theme', Object(WP_Theme))
#4 /var/www/mysite.com/wp-includes/class-wp-hook.php(300): Mlp_Duplicate_Blogs->wpmu_new_blog(27, 1)
#5 /var/www/mysite.com/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) in /var/www/mysite.com/wp-content/plugins/translation-cache/src/MoCache.php on line 119
```

**Comment by gmazzap** [comment]
Hi @ahmed-sigmalux 

Thanks, for reporting the issue. I pushed a fix on the branch `master`. Could you please test if it works for you? If so, I will release a new version.

**Comment by ahmed-sigmalux** [comment]
Yes, the fix appears to work.

I will post an update if we have any more trouble duplicating sites.

**Comment by bueltge** [comment]
I close them and release a new stable tag to include this also for users outside the dev master.
